ci:
  skip: [typos]

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.41.0
    hooks:
      - id: typos
  - repo: https://github.com/reteps/dockerfmt
    # run `pre-commit autoupdate` to pin the version
    rev: v0.3.9
    hooks:
      - id: dockerfmt
        args:
          # optional: add additional arguments here
          - --indent=4
          - --write
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--ignore-path=.prettierignore"]
