---
name: TooGoodToGo Home Assistant MQTT Bridge
version: 2.1.0
image: maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-{arch}
slug: tgtg-ha-mqtt-bridge
description: Publish TooGoodToGo stock as MQTT messages
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  mqtt:
    host: homeassistant
    port: 1883
    username: mqtt
    password: mqtt
  tgtg:
    email: me@example.com
    language: en-US
    polling_schedule: "*/10 * * * *"
  timezone: Europe/Berlin
  locale: en_us
  cleanup: true
schema:
  mqtt:
    host: str
    port: int
    username: str?
    password: str?
  tgtg:
    email: str
    language: str
    polling_schedule: str
  timezone: str?
  locale: str?
  cleanup: bool
stage: experimental
url: https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge
hassio_role: default
hassio_api: true
environment:
  DYNACONF_DATA_DIR: "/data/"
